export const CAMPAIGN_CARD_SELECT = `
  id,
  title,
  platform,
  type,
  category,
  thumbnail_url,
  campaign_image_variants,
  experience_details,
  campaign_options,
  total_recruitment,
  recruitment_start_date,
  end_date,
  first_selection_date,
  is_unlimited_recruitment,
  region,
  sub_region,
  created_at,
  status,
  applications(count)
`.replace(/\s+/g, ' ').trim();

export const CAMPAIGN_METADATA_SELECT = `
  id,
  title,
  thumbnail_url,
  campaign_image_variants,
  campaign_options
`.replace(/\s+/g, ' ').trim();

export const CAMPAIGN_DETAIL_SELECT = `
  id,
  created_by,
  title,
  thumbnail_url,
  campaign_image_variants,
  type,
  platform,
  region,
  sub_region,
  total_recruitment,
  recruitment_start_date,
  end_date,
  first_selection_date,
  is_unlimited_recruitment,
  status,
  campaign_options,
  created_at,
  description,
  experience_details,
  category,
  contact_phone,
  contact_method,
  store_locations,
  reward_per_person,
  campaign_images,
  product_options,
  option_config,
  product_name,
  applications(count)
`.replace(/\s+/g, ' ').trim();
