export const CAMPAIGN_CARD_SELECT = `
  id,
  title,
  platform,
  type,
  category,
  thumbnail_url,
  provision,
  experience_details,
  campaign_options,
  total_recruitment,
  recruitment_start_date,
  end_date,
  first_selection_date,
  review_deadline,
  is_unlimited_recruitment,
  region,
  sub_region,
  created_at,
  status,
  schedule_type,
  campaign_schedule_type,
  applications(count)
`.replace(/\s+/g, ' ').trim();

export const CAMPAIGN_METADATA_SELECT = `
  id,
  title,
  thumbnail_url,
  campaign_options
`.replace(/\s+/g, ' ').trim();

export const CAMPAIGN_DETAIL_SELECT = `
  id,
  created_by,
  title,
  thumbnail_url,
  type,
  platform,
  region,
  sub_region,
  total_recruitment,
  recruitment_start_date,
  end_date,
  first_selection_date,
  review_deadline,
  is_unlimited_recruitment,
  status,
  campaign_options,
  created_at,
  description,
  experience_details,
  purchase_notes,
  review_mission_content,
  mission_guide,
  keywords,
  photo_count,
  video_required,
  category,
  contact_phone,
  contact_method,
  advertiser_will_contact,
  visit_time,
  visit_time_negotiable,
  visit_days,
  visit_notes,
  store_locations,
  stores,
  reward_per_person,
  official_price,
  prohibited_words,
  sub_image_1,
  sub_image_2,
  campaign_images,
  product_options,
  option_config,
  product_name,
  schedule_type,
  campaign_schedule_type,
  applications(count)
`.replace(/\s+/g, ' ').trim();
